[deps]
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
UnicodeNext = "7b9d9d2f-29eb-4111-b31d-f1cfc33d1412"
WasmCodegen = "2a3016f4-244f-4553-97d3-d07103519a17"
WasmTools = "5d3dcfdb-8eae-450c-8bf9-209f91b22ad6"
WasmtimeRunner = "6ef1e157-63b0-4083-add8-761f9e147aa3"

[sources]
UnicodeNext = {path = "vendor/UnicodeNext"}
WasmCodegen = {path = "WasmCodegen"}
WasmTools = {path = "WasmTools"}
WasmtimeRunner = {path = "WasmtimeRunner"}
