name = "WasmCodegen"
uuid = "2a3016f4-244f-4553-97d3-d07103519a17"
authors = ["Keno Fischer <keno@juliahub.com> and contributors"]
version = "0.1.0"

[deps]
UnicodeNext = "7b9d9d2f-29eb-4111-b31d-f1cfc33d1412"
WasmTools = "5d3dcfdb-8eae-450c-8bf9-209f91b22ad6"

[compat]
julia = "1.12"

[sources]
UnicodeNext = {path = "../vendor/UnicodeNext"}
WasmTools = {path = "../WasmTools"}
WasmtimeRunner = {path = "../WasmtimeRunner"}

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WasmtimeRunner = "6ef1e157-63b0-4083-add8-761f9e147aa3"

[targets]
test = ["Test", "WasmtimeRunner"]
