name = "WasmtimeRunner"
uuid = "6ef1e157-63b0-4083-add8-761f9e147aa3"
authors = ["Keno Fischer <keno@juliahub.com> and contributors"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.10"

[sources]
WasmTools = {path = "../WasmTools"}

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WasmTools = "5d3dcfdb-8eae-450c-8bf9-209f91b22ad6"

[targets]
test = ["Test", "WasmTools"]
